cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/home/shimizu/ns-allinone-3.21/ns-3.21/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/home/shimizu/ns-allinone-3.21/ns-3.21/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139994073896464: cxx test.cc -> test.cc.1.o}\n[\'/usr/bin/g++\', \'-O3\', \'-g\', \'-Wall\', \'-Werror\', \'-march=native\', \'-fstrict-overflow\', \'-Wstrict-overflow=5\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DHAVE_PYTHON_H=1\', \'../test.cc\', \'-c\', \'-o\', \'test.cc.1.o\']\n'
